language: python
python:
- 2.7
- 3.4

notifications:
  email: false

env:
  global:
  - CONDA_ARGS="--yes"
  - PIP_ARGS=""
  - PYTEST_ARGS="--cov glue --no-optional-skip"
  - CONDA_BASE="pip numpy=1.8 scipy cython h5py pygments pyzmq scikit-image pandas sphinx=1.2.2 xlrd pillow pytest mock coverage"
  - PIP_BASE="pytest-cov coveralls pyavm sphinx-rtd-theme astrodendro awscli"
  - secure: NvQVc3XmmjXNVKrmaD31IgltsOImlnt3frAl4wU0pM223iejr7V57hz/V5Isx6sTANWEiRBMG27v2T8e5IiB7DQTxFUleZk3DWXQV1grw/GarEGUawXAgwDWpF0AE/7BRVJYqo2Elgaqf28+Jkun8ewvfPCiEROD2jWEpnZj+IQ=
  - secure: "SU9BYH8d9eNigypG3lC83s0NY6Mq9AHGKXyEGeXDtz1npJIC1KHdzPMP1v1K3dzCgl1p6ReMXPjZMCENyfNkad/xvzTzGk0Nu/4BjihrUPV6+ratVeLpv0JLm8ikh8q+sZURkdtzUOlds+Hfn5ku4LdpT87tcKHY9TINAGA34ZM="
  - AWS_ACCESS_KEY_ID: AKIAI2ERWDHLW3W24X3A
  - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY_ID

  matrix:
  - MPL_VER=1.3 ASTRO_VER=0.4 IPYTHON_VER=2
  - MPL_VER=1.4 ASTRO_VER=0.3 IPYTHON_VER=2
  - MPL_VER=1.4 ASTRO_VER=dev IPYTHON_VER=2

matrix:

    include:

        # The following configuration tests that glue functions with minimal
        # dependencies. The --no-deps is to prevent scipy from getting
        # installed as a pandas dependency.
        - python: 2.7
          env:
            - PYTEST_ARGS="--cov glue"
            - CONDA_BASE="pip setuptools numpy=1.8 pandas mock --no-deps"
            - IPYTHON_VER=None
            - ASTRO_VER=None
            - MPL_VER=1.4
            - PIP_BASE="pytest-cov coveralls"

        - python: 2.7
          env: MPL_VER=1.4 ASTRO_VER=0.4 IPYTHON_VER=2 DOC_TRIGGER=1 APP_TRIGGER=1

        - python: 2.7
          env: MPL_VER=1.4 ASTRO_VER=0.4 IPYTHON_VER=1.1

        - python: 2.7
          env: MPL_VER=1.4 ASTRO_VER=0.4 IPYTHON_VER=0.13

before_install:
- source .setup_conda.sh $TRAVIS_PYTHON_VERSION
# Deal with issue on Travis builders
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
# Setup system for headless GUI handling
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# setup tools to trigger mac buildbot
- if [ $APP_TRIGGER ]; then source .setup_app_trigger.sh; fi
- if [ $TRAVIS_BRANCH = master ]; then export S3_DIR=latest; else export S3_DIR=$TRAVIS_BRANCH; fi


install:
- conda install $CONDA_ARGS python=$TRAVIS_PYTHON_VERSION $CONDA_BASE
- if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then conda install $CONDA_ARGS python=$TRAVIS_PYTHON_VERSION pyside; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then conda install $CONDA_ARGS python=$TRAVIS_PYTHON_VERSION pyqt; fi
- LC_ALL=C pip install $PIP_ARGS $PIP_BASE
- if [[ $ASTRO_VER == dev ]]; then pip install -e git+git://github.com/astropy/astropy.git#egg=astropy; fi
- if [[ $ASTRO_VER != dev && $ASTRO_VER != None ]]; then conda install $CONDA_ARGS numpy=1.8 astropy=$ASTRO_VER; fi
- if [[ $IPYTHON_VER != None ]]; then conda install $CONDA_ARGS IPython=$IPYTHON_VER; fi
- if [[ $MPL_VER != None ]]; then conda install $CONDA_ARGS numpy=1.8 matplotlib=$MPL_VER; fi
- python setup.py install

script:
- py.test $PYTEST_ARGS glue
- if [ $DOC_TRIGGER ]; then cd doc && make html && cd ../; fi

after_success:
- coveralls
- if [ $APP_TRIGGER ]; then ./.trigger_app_build.sh; fi
- if [ $DOC_TRIGGER -a "$TRAVIS_SECURE_ENV_VARS = true" ]; then cd doc && make s3 && cd ../; fi
